services:
  devcontainer:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - ./:/haskell-mooc
      - ./starship.toml:/root/.config/starship.toml
      - ./config.fish:/root/.config/fish/config.fish
